const dishes = [
  {
    id: 1,
    name: 'Spicy seasoned seafood noodles',
    image: 'assets/item1.png',
    category: 'Hot Dishes',
    typeService: 'Dine In',
    price: 2.29,
    available: 20,
  },
  {
    id: 2,
    name: 'Salted Pasta with mushroom sauce',
    image: 'assets/item2.png',
    category: 'Hot Dishes',
    typeService: 'Dine In',
    price: 2.69,
    available: 11,
  },
  {
    id: 3,
    name: 'Beef dumpling in hot and sour soup',
    image: 'assets/item3.png',
    category: 'Hot Dishes',
    typeService: 'Dine In',
    price: 2.99,
    available: 16,
  },
  {
    id: 4,
    name: 'Healthy noodle with spinach leaf',
    image: 'assets/item4.png',
    category: 'Hot Dishes',
    typeService: 'Dine In',
    price: 3.29,
    available: 22,
  },
  {
    id: 5,
    name: 'Hot spicy fried rice with omelet',
    image: 'assets/item5.png',
    category: 'Hot Dishes',
    typeService: 'Dine In',
    price: 3.49,
    available: 13,
  },
  {
    id: 6,
    name: 'Spicy instant noodle with special omelette',
    image: 'assets/item6.png',
    category: 'Hot Dishes',
    typeService: 'Dine In',
    price: 3.59,
    available: 17,
  },
  {
    id: 7,
    name: 'Healthy noodle with spinach leaf',
    image: 'assets/item3.png',
    category: 'Hot Dishes',
    typeService: 'Dine In',
    price: 2.29,
    available: 22,
  },
  {
    id: 8,
    name: 'Hot spicy fried rice with omelet',
    image: 'assets/item2.png',
    category: 'Hot Dishes',
    typeService: 'Dine In',
    price: 3.29,
    available: 22,
  },
  {
    id: 9,
    name: 'Spicy instant noodle with special omelette',
    image: 'assets/item1.png',
    category: 'Hot Dishes',
    typeService: 'Dine In',
    price: 3.59,
    available: 22,
  },
  {
    id: 10,
    name: 'Hot spicy fried rice with omelet',
    image: 'assets/item2.png',
    category: 'Cold Dishes',
    typeService: 'Dine In',
    price: 3.29,
    available: 22,
  },
  {
    id: 11,
    name: 'Hot spicy fried rice with omelet',
    image: 'assets/item2.png',
    category: 'Cold Dishes',
    typeService: 'To Go',
    price: 3.29,
    available: 22,
  },
  {
    id: 12,
    name: 'Hot spicy fried rice with omelet',
    image: 'assets/item2.png',
    category: 'Cold Dishes',
    typeService: 'To Go',
    price: 3.29,
    available: 22,
  },
  {
    id: 13,
    name: 'Hot spicy fried rice with omelet',
    image: 'assets/item2.png',
    category: 'Cold Dishes',
    typeService: 'To Go',
    price: 3.29,
    available: 22,
  },
  {
    id: 14,
    name: 'Hot spicy fried rice with omelet',
    image: 'assets/item2.png',
    category: 'Cold Dishes',
    typeService: 'To Go',
    price: 3.29,
    available: 22,
  },
  {
    id: 15,
    name: 'Hot spicy fried rice with omelet',
    image: 'assets/item2.png',
    category: 'Cold Dishes',
    typeService: 'Delivery',
    price: 3.29,
    available: 22,
  },
  {
    id: 16,
    name: 'Hot spicy fried rice with omelet',
    image: 'assets/item2.png',
    category: 'Cold Dishes',
    typeService: 'Dine In',
    price: 3.29,
    available: 22,
  },
  {
    id: 17,
    name: 'Hot spicy fried rice with omelet',
    image: 'assets/item2.png',
    category: 'Cold Dishes',
    typeService: 'Dine In',
    price: 3.29,
    available: 22,
  },
];

export default dishes;
